//! Traits that define the core extension points for `easypdf-rs`.
//!
//! Includes `PdfModel`, `PdfReadListener`, `PdfWriteHandler`, and `PdfConverter`.

use crate::error::Result;

/// Trait for types that can be rendered as PDF content.
///
/// This is typically derived via `#[derive(PdfModel)]` rather than
/// implemented manually. It maps a Rust struct to PDF elements.
pub trait PdfModel {
    /// Render this model into PDF content.
    ///
    /// The implementation is generated by the derive macro and handles
    /// layout, positioning, and style application.
    fn render(&self) -> Result<Vec<RenderedElement>>;

    /// Return metadata for this model (page size, orientation, margins, etc.).
    fn metadata(&self) -> PdfModelMetadata;
}

/// Metadata associated with a `PdfModel` (typically from `#[pdf(...)]` attributes).
#[derive(Debug, Clone)]
pub struct PdfModelMetadata {
    /// Page size for the model.
    pub page_size: crate::enums::PageSize,
    /// Page orientation.
    pub orientation: crate::enums::Orientation,
    /// Page margins in points.
    pub margins: f64,
}

impl Default for PdfModelMetadata {
    fn default() -> Self {
        Self {
            page_size: crate::enums::PageSize::A4,
            orientation: crate::enums::Orientation::default(),
            margins: 72.0,
        }
    }
}

/// A rendered element produced by a [`PdfModel`].
///
/// This is the output of `PdfModel::render()`, representing one
/// positioned piece of content on a PDF page.
#[derive(Debug, Clone)]
pub enum RenderedElement {
    /// A text element at the given (x, y) position.
    Text {
        /// X coordinate in PDF points from bottom-left.
        x: f64,
        /// Y coordinate in PDF points from bottom-left.
        y: f64,
        /// The text content with formatting.
        text: crate::content::PdfText,
    },
    /// A table at the given (x, y) position.
    Table {
        /// X coordinate of table top-left.
        x: f64,
        /// Y coordinate of table top-left.
        y: f64,
        /// The table data and configuration.
        table: crate::content::PdfTable,
    },
    /// An image at the given (x, y) position.
    Image {
        /// X coordinate from bottom-left.
        x: f64,
        /// Y coordinate from bottom-left.
        y: f64,
        /// The image data.
        image: crate::content::PdfImage,
    },
}

// --- PdfReadListener ---

/// Event-driven listener for PDF reading operations.
///
/// Analogous to `ReadListener<T>` in easyexcel-rs. Called for
/// each page or text block encountered during reading.
pub trait PdfReadListener: Send {
    /// Called when a page starts being processed.
    fn on_page_start(&mut self, page_number: usize) -> Result<()> {
        let _ = page_number;
        Ok(())
    }

    /// Called for each text block extracted from a page.
    fn on_text(&mut self, page_number: usize, text: &str) -> Result<()>;

    /// Called when a page has been fully processed.
    fn on_page_end(&mut self, page_number: usize) -> Result<()> {
        let _ = page_number;
        Ok(())
    }

    /// Called after all pages have been processed.
    fn on_document_end(&mut self) -> Result<()> {
        Ok(())
    }
}

// --- PdfWriteHandler ---

/// Lifecycle hooks for PDF writing operations.
///
/// Analogous to `WriteHandler` in easyexcel-rs. Handlers are
/// called in order (by priority) at each stage of document creation.
pub trait PdfWriteHandler: Send {
    /// Called before the document is created.
    fn before_document(&mut self) -> Result<()> {
        Ok(())
    }

    /// Called before a new page is started.
    fn before_page(&mut self, page_number: usize) -> Result<()> {
        let _ = page_number;
        Ok(())
    }

    /// Called after a page is completed.
    fn after_page(&mut self, page_number: usize) -> Result<()> {
        let _ = page_number;
        Ok(())
    }

    /// Called after the document is finalized.
    fn after_document(&mut self) -> Result<()> {
        Ok(())
    }
}

// --- PdfConverter ---

/// Bidirectional converter between a Rust type `T` and a PDF string representation.
///
/// Analogous to `Converter<T>` in easyexcel-rs.
pub trait PdfConverter<T>: Send {
    /// Convert a Rust value to its PDF string representation.
    fn to_pdf_string(&self, value: &T) -> Result<String>;

    /// Convert a PDF string representation back to a Rust value.
    fn from_pdf_string(&self, s: &str) -> Result<T>;
}

// --- PdfEngine (C1) ---

/// Abstract PDF engine interface for backend swapping.
///
/// Allows different PDF backends (lopdf, printpdf, justpdf) to be used
/// interchangeably. Currently experimental — full abstraction awaits
/// a second mature engine implementation.
pub trait PdfEngine: Send + Sync {
    /// Human-readable engine name.
    fn name(&self) -> &str;

    /// Features supported by this engine.
    fn capabilities(&self) -> EngineCapabilities;
}

/// Describes which operations a PDF engine supports.
#[derive(Debug, Clone, Copy, Default)]
pub struct EngineCapabilities {
    /// Can create new PDF documents from scratch.
    pub create: bool,
    /// Can read and parse existing PDF documents.
    pub read: bool,
    /// Can manipulate (merge, split, rotate) existing PDFs.
    pub manipulate: bool,
    /// Can fill form fields in PDF templates.
    pub fill_forms: bool,
    /// Supports encryption.
    pub encrypt: bool,
    /// Supports digital signatures.
    pub sign: bool,
    /// Supports PDF/A validation.
    pub pdfa: bool,
}

impl EngineCapabilities {
    /// lopdf capabilities.
    #[must_use]
    pub const fn lopdf() -> Self {
        Self {
            create: false,
            read: true,
            manipulate: true,
            fill_forms: true,
            encrypt: false,
            sign: false,
            pdfa: false,
        }
    }

    /// printpdf capabilities.
    #[must_use]
    pub const fn printpdf() -> Self {
        Self {
            create: true,
            read: false,
            manipulate: false,
            fill_forms: false,
            encrypt: false,
            sign: false,
            pdfa: false,
        }
    }
}
